# Generated by Django 6.0.6 on 2026-06-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_truckstop_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='retail_price',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
