# Generated by Django 6.0.6 on 2026-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_fuelstation_opis_truckstop_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='retail_price',
            field=models.DecimalField(decimal_places=7, max_digits=8),
        ),
    ]
